core/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^pins/pin-form/$', TemplateView.as_view(template_name='core/pin_form.html'),
        name='pin-form'),
    url(r'^pins/tags/(?P<tag>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='tag-pins'),
    url(r'^pins/users/(?P<username>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='user-pins'),
    url(r'^(?P<pin>[0-9]+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='pin-detail'),
    url(r'^$', TemplateView.as_view(template_name='core/pins.html'),
        name='recent-pins'),
]

pinry/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.views.static import serve
from rest_framework.documentation import include_docs_urls

from core.views import drf_router


admin.autodiscover()


urlpatterns = [
    # drf api
    url(r'^api/v2/', include(drf_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace="rest_framework")),
    url(r'^api/v2/docs/', include_docs_urls(title='PinryAPI', schema_url='/')),

    # old api and views
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls', namespace='core')),
    url(r'', include('users.urls', namespace='users')),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
    ]

if settings.IS_TEST:
    urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^private/$', views.private, name='private'),
    url(r'^register/$', views.CreateUser.as_view(), name='register'),
    url(r'^login/$', login,
        {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

pinry/templates/base.html
<!DOCTYPE html>
{% load staticfiles compress %}
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
        <title>{% block title %}Pinry{% endblock %}</title>

        <link rel="shortcut icon" type="image/png" href="/static/favicon.png"/>

        <!-- CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"/>
        <link rel="stylesheet" href="https://unpkg.com/bootstrap@3.3.6/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="https://unpkg.com/dropzone@4.3.0/dist/min/dropzone.min.css"/>
        {% compress css %}
            <link rel="stylesheet" href="{% static "css/messages.css" %}"/>
            <link rel="stylesheet" href="{% static "css/lightbox.css" %}"/>
            <link rel="stylesheet" href="{% static "css/pinry.css" %}"/>
        {%  endcompress %}
        {% compress css inline %}
            {% block extra_css %}{% endblock %}
        {% endcompress %}
        <!-- End CSS -->

        <!-- Start JavaScript Variables -->
        <script>
        var apiLimitPerPage = {{ API_LIMIT_PER_PAGE }},
            errors = {% if not messages %}null,{% else %}[
                {% for message in messages %}{
                    tags: "{{ message.tags }}",
                    text: "{{ message }}"
                }{% endfor %}
            ],{% endif %}
            currentUser = {
                id: "{{ user.id }}",
                username: "{{ user.username }}",
                gravatar: "{{ user.gravatar }}"
            },
            pinFilter = "{{ request.resolver_match.kwargs.pin }}",
            tagFilter = "{{ request.resolver_match.kwargs.tag }}",
            userFilter = "{{ request.resolver_match.kwargs.username }}";
        </script>
        <!-- End JavaScript Variables -->
    </head>

    <body>
        <!-- Navigation -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'core:recent-pins' %}" class="navbar-brand">
                        <img src="{% static "img/logo-dark.png" %}" alt="Pinry"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a onclick="pinForm()">New Pin</a></li>
                            <li><a href="{% url 'users:logout' %}">Logout</a></li>
                            <li>{% include "includes/bookmarklet_link.html" %}</li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}">Login</a></li>
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Navigation -->

        <!-- Messages -->
        <ul id="messages"></ul>
        <!-- End Messages -->

        <!-- No Script -->
        <div id="noscript">
            <noscript>Scripting is not enabled in your browser, if you are using
                a plugin like NoScript *high five*! Our code is open source and
                you can view it on
                <a href="https://github.com/pinry/pinry/">GitHub</a>.
                <style>.spinner{display:none;}</style></noscript>
        </div>
        <!-- End No Script -->

        <!-- Content -->
        {% block yield %}{% endblock %}
        <!-- End Content -->

        <!-- Templates -->
        {% include "includes/messages.html" %}
        {% include "includes/lightbox.html" %}
        {% include "includes/pins.html" %}
        {% include "includes/pin_form.html" %}
        {% block extra_templates %}{% endblock %}
        <!-- End Templates -->

        <!-- JavaScript -->
        <script src="https://unpkg.com/jquery@2.2.4/dist/jquery.min.js"></script>
        <script src="https://unpkg.com/bootstrap@3.3.6/dist/js/bootstrap.min.js"></script>
        <script src="https://unpkg.com/handlebars@4.0.6/dist/handlebars.min.js"></script>
        <script src="https://unpkg.com/dropzone@4.3.0/dist/min/dropzone.min.js"></script>
        {% compress js %}
            <script src="{% static "js/helpers.js" %}"></script>
            <script src="{% static "js/messages.js" %}"></script>
            <script src="{% static "js/lightbox.js" %}"></script>
            <script src="{% static "js/pinry.js" %}"></script>
            <script src="{% static "js/pin-form.js" %}"></script>
        {% endcompress %}
        {% compress js inline %}
            {% block extra_js %}{% endblock %}
        {% endcompress %}
        <!-- End JavaScript -->
    </body>
</html>